"""
Chainlit UI for A/B Testing Agent

Provides a web-based chat interface for:
- Uploading CSV files
- Interacting with the A/B testing agent
- Viewing conversation history
- Displaying analysis results
- Showing interactive visualizations
"""

import logging
from pathlib import Path

import chainlit as cl
from dotenv import load_dotenv

from src import ABTestingAgent
from src.auth import is_auth_enabled, verify_credentials
from src.config import Config
from src.query_store_gc import run_startup_gc

load_dotenv()
logger = logging.getLogger(__name__)

_STARTUP_CONFIG = Config.from_env()
try:
    _STARTUP_CONFIG.validate()
    logger.info(
        "Startup config: model=%s temperature=%s file_size_threshold_mb=%.2f "
        "sql_row_limit=%d query_timeout_s=%.1f",
        _STARTUP_CONFIG.llm_model,
        _STARTUP_CONFIG.llm_temperature,
        _STARTUP_CONFIG.file_size_threshold_mb,
        _STARTUP_CONFIG.sql_default_row_limit,
        _STARTUP_CONFIG.query_timeout_seconds,
    )
except ValueError:
    logger.exception("Startup Config validation failed; continuing with defaults")

run_startup_gc(Path("output") / "query_store")


if is_auth_enabled():
    @cl.password_auth_callback
    def _auth(username: str, password: str):
        identity = verify_credentials(username, password)
        if identity is None:
            return None
        return cl.User(identifier=identity, metadata={"role": "user"})

    logger.info("Chainlit password auth ENABLED via STATAGENT_AUTH_* env vars")
else:
    logger.info("Chainlit password auth disabled (set STATAGENT_AUTH_USERNAME and STATAGENT_AUTH_PASSWORD to enable)")


def _ensure_chainlit_files_root() -> None:
    """Ensure Chainlit has a root directory for persisted element files."""
    Path(".files").mkdir(exist_ok=True)


def _session_query_store_path() -> str:
    """Derive a stable per-Chainlit-session SQLite path so reconnects can
    rehydrate persisted chat history. Falls back to the legacy random
    UUID path when no session id is available.
    """
    session_id = cl.user_session.get("id")
    if session_id is None:
        from uuid import uuid4

        session_id = uuid4().hex
        cl.user_session.set("id", session_id)
    return str(Path("output") / "query_store" / f"session-{session_id}.sqlite")


def get_or_create_agent() -> ABTestingAgent:
    """
    Return the session agent, creating it lazily when missing.

    This avoids hard dependency on on_chat_start callback initialization.
    """
    agent = cl.user_session.get("agent")
    if agent is None:
        agent = ABTestingAgent(query_store_path=_session_query_store_path())
        cl.user_session.set("agent", agent)
        cl.user_session.set("uploaded_file", None)
        logger.info(
            "Created session agent (restored_history=%d)",
            len(agent.session.state.chat_history),
        )
    return agent


async def display_charts(agent):
    """Display any charts generated by the agent"""
    charts = agent.get_charts()

    if charts:
        _ensure_chainlit_files_root()
        elements = []
        for name, fig in charts.items():
            # Create a Plotly element for each chart
            chart_name = name.replace("_", " ").title()
            elements.append(
                cl.Plotly(name=chart_name, figure=fig, display="inline")
            )

        if elements:
            await cl.Message(
                content="Here are the visualizations:",
                elements=elements
            ).send()

        # Clear charts after displaying
        agent.clear_charts()


@cl.on_message
async def main(message: cl.Message):
    """Handle incoming messages"""
    try:
        agent = get_or_create_agent()
        logger.info("Received chat message (has_elements=%s)", bool(message.elements))

        # Check for file attachments
        if message.elements:
            for element in message.elements:
                if element.name.endswith('.csv'):
                    file_path = element.path
                    cl.user_session.set("uploaded_file", file_path)
                    logger.info("Processing uploaded CSV (name=%s)", element.name)

                    status_message = cl.Message(content="Processing...")
                    await status_message.send()

                    user_text = message.content.strip() if message.content else ""
                    if user_text:
                        agent_message = f"User request: {user_text}\n\nCSV file path: {file_path}"
                    else:
                        agent_message = f"Load the CSV file at path: {file_path}"

                    response = await cl.make_async(agent.run)(agent_message)
                    status_message.content = response
                    await status_message.update()

                    await display_charts(agent)
                    return

        user_message = message.content
        msg = cl.Message(content="")
        await msg.send()

        response = await cl.make_async(agent.run)(user_message)
        msg.content = response
        await msg.update()

        await display_charts(agent)
    except Exception:
        logger.exception("Unhandled error while processing chat message")
        await cl.Message(
            content=(
                "Error processing request: Unable to handle this UI request right now. "
                "[error_code=UI_MESSAGE_HANDLING_FAILED]"
            )
        ).send()


@cl.on_settings_update
async def setup_agent(settings):
    """Handle settings updates"""
    logger.info("Chainlit settings updated")


# Custom action handlers for common operations
@cl.action_callback("run_full_analysis")
async def on_action_full_analysis(action):
    """Callback for full analysis action button"""
    agent = get_or_create_agent()

    await cl.Message(content="Running full segmented analysis...").send()

    response = await cl.make_async(agent.run)(
        "Run a full A/B test analysis for all segments and provide a comprehensive summary"
    )

    await cl.Message(content=response).send()

    # Display any charts
    await display_charts(agent)


@cl.action_callback("show_data_summary")
async def on_action_data_summary(action):
    """Callback for data summary action button"""
    agent = get_or_create_agent()

    response = await cl.make_async(agent.run)(
        "Show me a summary of the loaded data"
    )

    await cl.Message(content=response).send()


@cl.action_callback("show_charts")
async def on_action_show_charts(action):
    """Callback for showing charts"""
    agent = get_or_create_agent()

    response = await cl.make_async(agent.run)(
        "Generate all charts for the analysis"
    )

    await cl.Message(content=response).send()

    # Display the charts
    await display_charts(agent)


@cl.action_callback("clear_conversation")
async def on_action_clear(action):
    """Callback for clearing conversation"""
    agent = cl.user_session.get("agent")
    if agent is not None:
        agent.clear_memory()
        agent.clear_charts()

    await cl.Message(content="Conversation history cleared. You can start fresh!").send()


# Enable file upload
@cl.on_chat_resume
async def on_chat_resume():
    """Handle chat resume — rehydrate the agent from the persisted SQLite."""
    agent = ABTestingAgent(query_store_path=_session_query_store_path())
    cl.user_session.set("agent", agent)
    logger.info(
        "Resumed chat session (restored_history=%d)",
        len(agent.session.state.chat_history),
    )


# Configure Chainlit settings
if __name__ == "__main__":
    from chainlit.cli import run_chainlit
    run_chainlit(__file__)
